// <auto-generated />
using System;
using ClipFunc.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClipFunc.DataContext.Migrations
{
    [DbContext(typeof(ClipFuncContext))]
    partial class ClipFuncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClipFunc.DataContext.Models.AccessTokenModel", b =>
                {
                    b.Property<string>("AccessToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("AccessToken");

                    b.ToTable("AccessTokens", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.ClipModel", b =>
                {
                    b.Property<string>("ClipId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClipCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VodOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClipId");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GameId");

                    b.ToTable("Clips", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.GameModel", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxArtUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IgdbId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.UserModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.ClipModel", b =>
                {
                    b.HasOne("ClipFunc.DataContext.Models.UserModel", "Broadcaster")
                        .WithMany("ClipsAsBroadcaster")
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClipFunc.DataContext.Models.UserModel", "Creator")
                        .WithMany("CreatedClips")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClipFunc.DataContext.Models.GameModel", "Game")
                        .WithMany("Clips")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Broadcaster");

                    b.Navigation("Creator");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.GameModel", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("ClipFunc.DataContext.Models.UserModel", b =>
                {
                    b.Navigation("ClipsAsBroadcaster");

                    b.Navigation("CreatedClips");
                });
#pragma warning restore 612, 618
        }
    }
}
